language: node_js
node_js:
  - "10"
addons:
  chrome: stable
  firefox: latest
script:
  - yarn
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
after_success: 'yarn run coveralls'
